### ISSUE TITLE
More docs would be nice!

### ISSUE THREAD

**Issue by brianorwhatever** [StarlaneStudios/cirql#4]
**Describe your feature request**
There isn't much available in your docs.. but the library appears to work great. Would be nice to know how to use it

**Comment by macjuul** [comment]
You're totally right! I've been fairly busy lately but I'll find some time to expand the docs as soon as possible.

If there's anything in specific you'd like to see documented feel free to let me know

**Comment by brianorwhatever** [comment]
no worries, I think filling out the API references that are blank right now would be great

**Comment by macjuul** [comment]
We are in the process of expanding our documentation and inviting community help on doing so (See #6)
