### ISSUE TITLE
timeNow() is not exported from cirql

### ISSUE THREAD

**Issue by itzjustalan** [StarlaneStudios/cirql#9]
**Describe the bug**
Module '"cirql"' has no exported member 'timeNow'.

**Example**
https://cirql.starlane.studio/docs/guide/basic-usage#raw-query-values--operators
```
const profile = await cirql.execute({ 
    query: create('organisation').setAll({
        name: 'Example',
        isEnabled: eq('$enable'),
        createdAt: eq(timeNow()) // time::now()
    }),
    schema: Organisation,
    params: {
        enable: true
    }
});
```

**Expected behavior**
for it to work

**Environment:**
 - OS: Windows 10
 - Version: 0.6.6
 - Node Version: v18.12.1

**Comment by macjuul** [comment]
We renamed this function a few releases ago. The docs will be updated to reflect this soon.

You can now use
```ts
import { time } from 'cirql';

time.now()
```
